---
driver:
  name: vagrant
  customize:
   memory: 2048
   cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec
  require_chef_omnibus: latest
platforms:
  - name: rhel7
    driver:
     box: target/rhel7
     box_url: file///c/Box_files/rhel7-2016.04.15.box

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    attributes:
